#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Mode {
    Acc,
    Imm,
    Zp,
    Zpx,
    Zpy,
    Zi,
    Zix,
    Ziy,
    Abs,
    Ax,
    Ay,
    Ind,
    Ix,
    Imp,
    Rel,
}

/// 6502 instruction names, including the 65C02 forms the legacy assembler encodes.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Mnemonic {
    Adc,
    And,
    Asl,
    Bit,
    Cmp,
    Cpx,
    Cpy,
    Dec,
    Eor,
    Inc,
    Jmp,
    Jsr,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Ora,
    Rol,
    Ror,
    Sbc,
    Sta,
    Stx,
    Sty,
    Bcc,
    Bcs,
    Beq,
    Bmi,
    Bne,
    Bpl,
    Bvc,
    Bvs,
    Brk,
    Clc,
    Cld,
    Cli,
    Clv,
    Dex,
    Dey,
    Inx,
    Iny,
    Nop,
    Pha,
    Php,
    Pla,
    Plp,
    Rti,
    Rts,
    Sec,
    Sed,
    Sei,
    Tax,
    Tay,
    Tsx,
    Txa,
    Txs,
    Tya,
}

impl Mnemonic {
    pub(crate) const ALL: [Self; 56] = [
        Self::Adc,
        Self::And,
        Self::Asl,
        Self::Bit,
        Self::Cmp,
        Self::Cpx,
        Self::Cpy,
        Self::Dec,
        Self::Eor,
        Self::Inc,
        Self::Jmp,
        Self::Jsr,
        Self::Lda,
        Self::Ldx,
        Self::Ldy,
        Self::Lsr,
        Self::Ora,
        Self::Rol,
        Self::Ror,
        Self::Sbc,
        Self::Sta,
        Self::Stx,
        Self::Sty,
        Self::Bcc,
        Self::Bcs,
        Self::Beq,
        Self::Bmi,
        Self::Bne,
        Self::Bpl,
        Self::Bvc,
        Self::Bvs,
        Self::Brk,
        Self::Clc,
        Self::Cld,
        Self::Cli,
        Self::Clv,
        Self::Dex,
        Self::Dey,
        Self::Inx,
        Self::Iny,
        Self::Nop,
        Self::Pha,
        Self::Php,
        Self::Pla,
        Self::Plp,
        Self::Rti,
        Self::Rts,
        Self::Sec,
        Self::Sed,
        Self::Sei,
        Self::Tax,
        Self::Tay,
        Self::Tsx,
        Self::Txa,
        Self::Txs,
        Self::Tya,
    ];

    pub(crate) const fn name(self) -> &'static str {
        match self {
            Self::Adc => "ADC",
            Self::And => "AND",
            Self::Asl => "ASL",
            Self::Bit => "BIT",
            Self::Cmp => "CMP",
            Self::Cpx => "CPX",
            Self::Cpy => "CPY",
            Self::Dec => "DEC",
            Self::Eor => "EOR",
            Self::Inc => "INC",
            Self::Jmp => "JMP",
            Self::Jsr => "JSR",
            Self::Lda => "LDA",
            Self::Ldx => "LDX",
            Self::Ldy => "LDY",
            Self::Lsr => "LSR",
            Self::Ora => "ORA",
            Self::Rol => "ROL",
            Self::Ror => "ROR",
            Self::Sbc => "SBC",
            Self::Sta => "STA",
            Self::Stx => "STX",
            Self::Sty => "STY",
            Self::Bcc => "BCC",
            Self::Bcs => "BCS",
            Self::Beq => "BEQ",
            Self::Bmi => "BMI",
            Self::Bne => "BNE",
            Self::Bpl => "BPL",
            Self::Bvc => "BVC",
            Self::Bvs => "BVS",
            Self::Brk => "BRK",
            Self::Clc => "CLC",
            Self::Cld => "CLD",
            Self::Cli => "CLI",
            Self::Clv => "CLV",
            Self::Dex => "DEX",
            Self::Dey => "DEY",
            Self::Inx => "INX",
            Self::Iny => "INY",
            Self::Nop => "NOP",
            Self::Pha => "PHA",
            Self::Php => "PHP",
            Self::Pla => "PLA",
            Self::Plp => "PLP",
            Self::Rti => "RTI",
            Self::Rts => "RTS",
            Self::Sec => "SEC",
            Self::Sed => "SED",
            Self::Sei => "SEI",
            Self::Tax => "TAX",
            Self::Tay => "TAY",
            Self::Tsx => "TSX",
            Self::Txa => "TXA",
            Self::Txs => "TXS",
            Self::Tya => "TYA",
        }
    }

    /// Parses an upper-case instruction name.
    pub(crate) fn parse(name: &str) -> Option<Self> {
        Some(match name {
            "ADC" => Self::Adc,
            "AND" => Self::And,
            "ASL" => Self::Asl,
            "BIT" => Self::Bit,
            "CMP" => Self::Cmp,
            "CPX" => Self::Cpx,
            "CPY" => Self::Cpy,
            "DEC" => Self::Dec,
            "EOR" => Self::Eor,
            "INC" => Self::Inc,
            "JMP" => Self::Jmp,
            "JSR" => Self::Jsr,
            "LDA" => Self::Lda,
            "LDX" => Self::Ldx,
            "LDY" => Self::Ldy,
            "LSR" => Self::Lsr,
            "ORA" => Self::Ora,
            "ROL" => Self::Rol,
            "ROR" => Self::Ror,
            "SBC" => Self::Sbc,
            "STA" => Self::Sta,
            "STX" => Self::Stx,
            "STY" => Self::Sty,
            "BCC" => Self::Bcc,
            "BCS" => Self::Bcs,
            "BEQ" => Self::Beq,
            "BMI" => Self::Bmi,
            "BNE" => Self::Bne,
            "BPL" => Self::Bpl,
            "BVC" => Self::Bvc,
            "BVS" => Self::Bvs,
            "BRK" => Self::Brk,
            "CLC" => Self::Clc,
            "CLD" => Self::Cld,
            "CLI" => Self::Cli,
            "CLV" => Self::Clv,
            "DEX" => Self::Dex,
            "DEY" => Self::Dey,
            "INX" => Self::Inx,
            "INY" => Self::Iny,
            "NOP" => Self::Nop,
            "PHA" => Self::Pha,
            "PHP" => Self::Php,
            "PLA" => Self::Pla,
            "PLP" => Self::Plp,
            "RTI" => Self::Rti,
            "RTS" => Self::Rts,
            "SEC" => Self::Sec,
            "SED" => Self::Sed,
            "SEI" => Self::Sei,
            "TAX" => Self::Tax,
            "TAY" => Self::Tay,
            "TSX" => Self::Tsx,
            "TXA" => Self::Txa,
            "TXS" => Self::Txs,
            "TYA" => Self::Tya,
            _ => return None,
        })
    }

    pub(crate) fn opcode(self, mode: Mode) -> Option<u8> {
        self.row()
            .iter()
            .find_map(|(m, code)| (*m == mode).then_some(*code))
    }

    fn row(self) -> &'static [(Mode, u8)] {
        use Mode::*;
        match self {
            Self::Adc => &[
                (Imm, 0x69),
                (Zp, 0x65),
                (Zpx, 0x75),
                (Zi, 0x72),
                (Zix, 0x61),
                (Ziy, 0x71),
                (Abs, 0x6d),
                (Ax, 0x7d),
                (Ay, 0x79),
            ],
            Self::And => &[
                (Imm, 0x29),
                (Zp, 0x25),
                (Zpx, 0x35),
                (Zi, 0x32),
                (Zix, 0x21),
                (Ziy, 0x31),
                (Abs, 0x2d),
                (Ax, 0x3d),
                (Ay, 0x39),
            ],
            Self::Asl => &[
                (Acc, 0x0a),
                (Zp, 0x06),
                (Zpx, 0x16),
                (Abs, 0x0e),
                (Ax, 0x1e),
            ],
            Self::Bit => &[
                (Imm, 0x89),
                (Zp, 0x24),
                (Zpx, 0x34),
                (Abs, 0x2c),
                (Ax, 0x3c),
            ],
            Self::Cmp => &[
                (Imm, 0xc9),
                (Zp, 0xc5),
                (Zpx, 0xd5),
                (Zi, 0xd2),
                (Zix, 0xc1),
                (Ziy, 0xd1),
                (Abs, 0xcd),
                (Ax, 0xdd),
                (Ay, 0xd9),
            ],
            Self::Cpx => &[(Imm, 0xe0), (Zp, 0xe4), (Abs, 0xec)],
            Self::Cpy => &[(Imm, 0xc0), (Zp, 0xc4), (Abs, 0xcc)],
            Self::Dec => &[
                (Acc, 0x3a),
                (Zp, 0xc6),
                (Zpx, 0xd6),
                (Abs, 0xce),
                (Ax, 0xde),
            ],
            Self::Eor => &[
                (Imm, 0x49),
                (Zp, 0x45),
                (Zpx, 0x55),
                (Zi, 0x52),
                (Zix, 0x41),
                (Ziy, 0x51),
                (Abs, 0x4d),
                (Ax, 0x5d),
                (Ay, 0x59),
            ],
            Self::Inc => &[
                (Acc, 0x1a),
                (Zp, 0xe6),
                (Zpx, 0xf6),
                (Abs, 0xee),
                (Ax, 0xfe),
            ],
            Self::Jmp => &[(Abs, 0x4c), (Ind, 0x6c), (Ix, 0x7c)],
            Self::Jsr => &[(Abs, 0x20)],
            Self::Lda => &[
                (Imm, 0xa9),
                (Zp, 0xa5),
                (Zpx, 0xb5),
                (Zi, 0xb2),
                (Zix, 0xa1),
                (Ziy, 0xb1),
                (Abs, 0xad),
                (Ax, 0xbd),
                (Ay, 0xb9),
            ],
            Self::Ldx => &[
                (Imm, 0xa2),
                (Zp, 0xa6),
                (Zpy, 0xb6),
                (Abs, 0xae),
                (Ay, 0xbe),
            ],
            Self::Ldy => &[
                (Imm, 0xa0),
                (Zp, 0xa4),
                (Zpx, 0xb4),
                (Abs, 0xac),
                (Ax, 0xbc),
            ],
            Self::Lsr => &[
                (Acc, 0x4a),
                (Zp, 0x46),
                (Zpx, 0x56),
                (Abs, 0x4e),
                (Ax, 0x5e),
            ],
            Self::Ora => &[
                (Imm, 0x09),
                (Zp, 0x05),
                (Zpx, 0x15),
                (Zi, 0x12),
                (Zix, 0x01),
                (Ziy, 0x11),
                (Abs, 0x0d),
                (Ax, 0x1d),
                (Ay, 0x19),
            ],
            Self::Rol => &[
                (Acc, 0x2a),
                (Zp, 0x26),
                (Zpx, 0x36),
                (Abs, 0x2e),
                (Ax, 0x3e),
            ],
            Self::Ror => &[
                (Acc, 0x6a),
                (Zp, 0x66),
                (Zpx, 0x76),
                (Abs, 0x6e),
                (Ax, 0x7e),
            ],
            Self::Sbc => &[
                (Imm, 0xe9),
                (Zp, 0xe5),
                (Zpx, 0xf5),
                (Zi, 0xf2),
                (Zix, 0xe1),
                (Ziy, 0xf1),
                (Abs, 0xed),
                (Ax, 0xfd),
                (Ay, 0xf9),
            ],
            Self::Sta => &[
                (Zp, 0x85),
                (Zpx, 0x95),
                (Zi, 0x92),
                (Zix, 0x81),
                (Ziy, 0x91),
                (Abs, 0x8d),
                (Ax, 0x9d),
                (Ay, 0x99),
            ],
            Self::Stx => &[(Zp, 0x86), (Zpy, 0x96), (Abs, 0x8e)],
            Self::Sty => &[(Zp, 0x84), (Zpx, 0x94), (Abs, 0x8c)],
            Self::Bcc => &[(Rel, 0x90)],
            Self::Bcs => &[(Rel, 0xb0)],
            Self::Beq => &[(Rel, 0xf0)],
            Self::Bmi => &[(Rel, 0x30)],
            Self::Bne => &[(Rel, 0xd0)],
            Self::Bpl => &[(Rel, 0x10)],
            Self::Bvc => &[(Rel, 0x50)],
            Self::Bvs => &[(Rel, 0x70)],
            Self::Brk => &[(Imp, 0x00)],
            Self::Clc => &[(Imp, 0x18)],
            Self::Cld => &[(Imp, 0xd8)],
            Self::Cli => &[(Imp, 0x58)],
            Self::Clv => &[(Imp, 0xb8)],
            Self::Dex => &[(Imp, 0xca)],
            Self::Dey => &[(Imp, 0x88)],
            Self::Inx => &[(Imp, 0xe8)],
            Self::Iny => &[(Imp, 0xc8)],
            Self::Nop => &[(Imp, 0xea)],
            Self::Pha => &[(Imp, 0x48)],
            Self::Php => &[(Imp, 0x08)],
            Self::Pla => &[(Imp, 0x68)],
            Self::Plp => &[(Imp, 0x28)],
            Self::Rti => &[(Imp, 0x40)],
            Self::Rts => &[(Imp, 0x60)],
            Self::Sec => &[(Imp, 0x38)],
            Self::Sed => &[(Imp, 0xf8)],
            Self::Sei => &[(Imp, 0x78)],
            Self::Tax => &[(Imp, 0xaa)],
            Self::Tay => &[(Imp, 0xa8)],
            Self::Tsx => &[(Imp, 0xba)],
            Self::Txa => &[(Imp, 0x8a)],
            Self::Txs => &[(Imp, 0x9a)],
            Self::Tya => &[(Imp, 0x98)],
        }
    }
}
