#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum Mode {
    Acc,
    Imm,
    Zp,
    Zpx,
    Zpy,
    Zi,
    Zix,
    Ziy,
    Abs,
    Ax,
    Ay,
    Ind,
    Ix,
    Imp,
    Rel,
}

pub(crate) fn opcode(name: &str, mode: Mode) -> Option<u8> {
    use Mode::*;
    let row: &[(Mode, u8)] = match name {
        "ADC" => &[
            (Imm, 0x69),
            (Zp, 0x65),
            (Zpx, 0x75),
            (Zi, 0x72),
            (Zix, 0x61),
            (Ziy, 0x71),
            (Abs, 0x6d),
            (Ax, 0x7d),
            (Ay, 0x79),
        ],
        "AND" => &[
            (Imm, 0x29),
            (Zp, 0x25),
            (Zpx, 0x35),
            (Zi, 0x32),
            (Zix, 0x21),
            (Ziy, 0x31),
            (Abs, 0x2d),
            (Ax, 0x3d),
            (Ay, 0x39),
        ],
        "ASL" => &[
            (Acc, 0x0a),
            (Zp, 0x06),
            (Zpx, 0x16),
            (Abs, 0x0e),
            (Ax, 0x1e),
        ],
        "BIT" => &[
            (Imm, 0x89),
            (Zp, 0x24),
            (Zpx, 0x34),
            (Abs, 0x2c),
            (Ax, 0x3c),
        ],
        "CMP" => &[
            (Imm, 0xc9),
            (Zp, 0xc5),
            (Zpx, 0xd5),
            (Zi, 0xd2),
            (Zix, 0xc1),
            (Ziy, 0xd1),
            (Abs, 0xcd),
            (Ax, 0xdd),
            (Ay, 0xd9),
        ],
        "CPX" => &[(Imm, 0xe0), (Zp, 0xe4), (Abs, 0xec)],
        "CPY" => &[(Imm, 0xc0), (Zp, 0xc4), (Abs, 0xcc)],
        "DEC" => &[
            (Acc, 0x3a),
            (Zp, 0xc6),
            (Zpx, 0xd6),
            (Abs, 0xce),
            (Ax, 0xde),
        ],
        "EOR" => &[
            (Imm, 0x49),
            (Zp, 0x45),
            (Zpx, 0x55),
            (Zi, 0x52),
            (Zix, 0x41),
            (Ziy, 0x51),
            (Abs, 0x4d),
            (Ax, 0x5d),
            (Ay, 0x59),
        ],
        "INC" => &[
            (Acc, 0x1a),
            (Zp, 0xe6),
            (Zpx, 0xf6),
            (Abs, 0xee),
            (Ax, 0xfe),
        ],
        "JMP" => &[(Abs, 0x4c), (Ind, 0x6c), (Ix, 0x7c)],
        "JSR" => &[(Abs, 0x20)],
        "LDA" => &[
            (Imm, 0xa9),
            (Zp, 0xa5),
            (Zpx, 0xb5),
            (Zi, 0xb2),
            (Zix, 0xa1),
            (Ziy, 0xb1),
            (Abs, 0xad),
            (Ax, 0xbd),
            (Ay, 0xb9),
        ],
        "LDX" => &[
            (Imm, 0xa2),
            (Zp, 0xa6),
            (Zpy, 0xb6),
            (Abs, 0xae),
            (Ay, 0xbe),
        ],
        "LDY" => &[
            (Imm, 0xa0),
            (Zp, 0xa4),
            (Zpx, 0xb4),
            (Abs, 0xac),
            (Ax, 0xbc),
        ],
        "LSR" => &[
            (Acc, 0x4a),
            (Zp, 0x46),
            (Zpx, 0x56),
            (Abs, 0x4e),
            (Ax, 0x5e),
        ],
        "ORA" => &[
            (Imm, 0x09),
            (Zp, 0x05),
            (Zpx, 0x15),
            (Zi, 0x12),
            (Zix, 0x01),
            (Ziy, 0x11),
            (Abs, 0x0d),
            (Ax, 0x1d),
            (Ay, 0x19),
        ],
        "ROL" => &[
            (Acc, 0x2a),
            (Zp, 0x26),
            (Zpx, 0x36),
            (Abs, 0x2e),
            (Ax, 0x3e),
        ],
        "ROR" => &[
            (Acc, 0x6a),
            (Zp, 0x66),
            (Zpx, 0x76),
            (Abs, 0x6e),
            (Ax, 0x7e),
        ],
        "SBC" => &[
            (Imm, 0xe9),
            (Zp, 0xe5),
            (Zpx, 0xf5),
            (Zi, 0xf2),
            (Zix, 0xe1),
            (Ziy, 0xf1),
            (Abs, 0xed),
            (Ax, 0xfd),
            (Ay, 0xf9),
        ],
        "STA" => &[
            (Zp, 0x85),
            (Zpx, 0x95),
            (Zi, 0x92),
            (Zix, 0x81),
            (Ziy, 0x91),
            (Abs, 0x8d),
            (Ax, 0x9d),
            (Ay, 0x99),
        ],
        "STX" => &[(Zp, 0x86), (Zpy, 0x96), (Abs, 0x8e)],
        "STY" => &[(Zp, 0x84), (Zpx, 0x94), (Abs, 0x8c)],
        "BCC" => &[(Rel, 0x90)],
        "BCS" => &[(Rel, 0xb0)],
        "BEQ" => &[(Rel, 0xf0)],
        "BMI" => &[(Rel, 0x30)],
        "BNE" => &[(Rel, 0xd0)],
        "BPL" => &[(Rel, 0x10)],
        "BVC" => &[(Rel, 0x50)],
        "BVS" => &[(Rel, 0x70)],
        "BRK" => &[(Imp, 0x00)],
        "CLC" => &[(Imp, 0x18)],
        "CLD" => &[(Imp, 0xd8)],
        "CLI" => &[(Imp, 0x58)],
        "CLV" => &[(Imp, 0xb8)],
        "DEX" => &[(Imp, 0xca)],
        "DEY" => &[(Imp, 0x88)],
        "INX" => &[(Imp, 0xe8)],
        "INY" => &[(Imp, 0xc8)],
        "NOP" => &[(Imp, 0xea)],
        "PHA" => &[(Imp, 0x48)],
        "PHP" => &[(Imp, 0x08)],
        "PLA" => &[(Imp, 0x68)],
        "PLP" => &[(Imp, 0x28)],
        "RTI" => &[(Imp, 0x40)],
        "RTS" => &[(Imp, 0x60)],
        "SEC" => &[(Imp, 0x38)],
        "SED" => &[(Imp, 0xf8)],
        "SEI" => &[(Imp, 0x78)],
        "TAX" => &[(Imp, 0xaa)],
        "TAY" => &[(Imp, 0xa8)],
        "TSX" => &[(Imp, 0xba)],
        "TXA" => &[(Imp, 0x8a)],
        "TXS" => &[(Imp, 0x9a)],
        "TYA" => &[(Imp, 0x98)],
        _ => return None,
    };
    row.iter().find_map(|(m, v)| (*m == mode).then_some(*v))
}
